[package]
name = "tinysearch"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
version = "0.3.1"
edition = "2018"
description = "A tiny search engine for static websites"
license = "Apache-2.0/MIT"
documentation = "https://github.com/mre/tinysearch/blob/master/README.md"
homepage = "https://github.com/mre/tinysearch"

[dependencies]
structopt = "0.3.5"
structopt-derive = "0.3.3"
tinysearch-shared = { path = "../shared", version = "0.2.1" }
log = "0.4.8"
reqwest = "0.9.22"
semver = "0.9.0"
serde_json = "1.0.42"
flate2 = "1.0.13"
tar = "0.4.26"
strip_markdown = "0.1.0"
tinysearch-cuckoofilter = "0.4.1"
walkdir = "2.2.9"
failure = "0.1.6"
tempdir = "0.3.7"
serde = "1.0.103"
serde_derive = "1.0.102"
lazy_static = "1.4.0"
